#!/bin/bash
backlight_dir="/sys/class/backlight/intel_backlight"

# Utiliser mkdir pour éviter plusieurs appels simultanés au script
#
lock_dir="/tmp/brightnessctl.exclusivelock"
if mkdir "$lock_dir" 2>/dev/null; then
    trap 'rm -rf "$lock_dir"; exit' 0 1 2 3 13 15
    current=$(cat "$backlight_dir/actual_brightness")
    max=$(cat "$backlight_dir/max_brightness")
    step=$(( max / 100 ))
    is_number='^[0-9]+$'
    if ([ "$1" = "-set" ] || [ "$1" = "-inc" ] || [ "$1" = "-dec" ]) && [[ $2 =~ $is_number ]]; then
        if [ "$1" = "-set" ]; then
            new=$(( $2 * step ))
        elif [ "$1" = "-inc" ]; then
            new=$(( current + ($2 * step) ))
        elif [ "$1" = "-dec" ]; then
            new=$(( current - ($2 * step) ))
        fi
    fi
    if [ "x$new" != "x" ]; then
        if [ "$new" -lt 0 ]; then
            new="0"
        elif [ "$new" -gt "$max" ]; then
            new="$max"
        fi
        echo "$new" > "$backlight_dir/brightness"
        if [ "$1" = "-set" ] || [ "$1" = "-inc" ] || [ "$1" = "-dec" ]; then
            level=$(( new / step ))
            dunstify -i /usr/share/icons/HighContrast/16x16/status/display-brightness.png -r 8029 -t 2000 "Luminosité : ${level}%"
        fi
    fi
fi
