#!/bin/bash
backlight_dir="/sys/class/backlight/intel_backlight"
backlight_tmp="${HOME}/.cache/backlight_tmp"

# Utiliser mkdir pour éviter plusieurs appels simultanés au script
#
lock_dir="/tmp/brightnessctl.exclusivelock"
if mkdir "$lock_dir" 2>/dev/null; then
    trap 'rm -rf "$lock_dir"; exit' 0 1 2 3 13 15
    current=$(cat "$backlight_dir/actual_brightness")
    if [ "$1" = "-save" ]; then
        echo "$current" > "$backlight_tmp"
    else
        max=$(cat "$backlight_dir/max_brightness")
        step=$(( max / 100 ))
        is_number='^[0-9]+$'
        if [ "$1" = "-restore" ]; then
            if [ -f "$backlight_tmp" ]; then
                new=$(cat "$backlight_tmp")
            fi
            # Une valeur trop petite ne suffira pas à rétablir la luminosité
            if [ $new -lt $(( 3 * step )) ]; then
                new=$(( 3 * step ))
            fi
        elif [ "$1" = "-dim" ]; then
            new="0"
        elif ([ "$1" = "-set" ] || [ "$1" = "-inc" ] || [ "$1" = "-dec" ]) && [[ $2 =~ $is_number ]]; then
            if [ "$1" = "-set" ]; then
                new=$(( $2 * step ))
            elif [ "$1" = "-inc" ]; then
                new=$(( current + ($2 * step) ))
            elif [ "$1" = "-dec" ]; then
                new=$(( current - ($2 * step) ))
            fi
        fi
        if [ "x$new" != "x" ]; then
            if [ "$new" -lt 0 ]; then
                new="0"
            elif [ "$new" -gt "$max" ]; then
                new="$max"
            fi
            echo "$new" > "$backlight_dir/brightness"
            if [ "$1" = "-set" ] || [ "$1" = "-inc" ] || [ "$1" = "-dec" ]; then
                level=$(( new / step ))
                dunstify -i /usr/share/icons/Adwaita/scalable/status/display-brightness-symbolic.svg -r 8192 -t 2000 "Luminosité : ${level}%"
            fi
        fi
    fi
fi
