#!/bin/bash

# Centralisation de variables et de fonctions pour éviter des modifications
# dans de trop nombreux fichiers en cas de changement de certains programmes
# (par ex. changement de terminal, de shell, etc.)

# Variables communes
default_path="/usr/bin/"
scripts_path="/usr/local/bin/pipemenus/"

# Écrire (ex. pipemenu) d'ouvrir un terminal pour éditer un fichier
function edit_file() {
    echo "${default_path}urxvt -e ${default_path}bash -l -c \"tmux new-session ${default_path}vim ${1}\""
}

# Écrire (ex. pipemenu) d'ouvrir un terminal pour lister le contenu d'un fichier
function cat_file() {
    echo "${default_path}urxvt -e ${default_path}bash -l -c \"${default_path}cat ${1} | ${default_path}less\""
}

# Écrire d'ouvrir un terminal pour y lancer un programme
function display_file() {
    echo "${default_path}urxvt -e ${default_path}bash -l -c \"${1} | ${default_path}less\""
}

# Ouvrir un terminal pour éditer un fichier
function direct_edit_file() {
    ${default_path}urxvt -e ${default_path}bash -l -c "tmux new-session ${default_path}vim ${1}"
}

# Ouvrir un terminal pour comparer deux fichiers
function direct_compare_files() {
    ${default_path}urxvt -e ${default_path}bash -l -c "vimdiff ${1} ${2}"
}
