#!/bin/bash

file=1
while [ "$file" ]; do
    file=$(ls -a -1 --group-directories-first | /usr/bin/dmenu -b -i -p "$(basename $(pwd))")
    if [ -e "$file" ]; then
        owd=$(pwd)
        if [ -d "$file" ]; then
            cd "$file"
        else [ -f "$file" ]
            if which whippet &>/dev/null; then
                exec /usr/bin/whippet -M "$owd/$file" &
                unset file
            elif which xdg-open &>/dev/null; then
                exec /usr/bin/xdg-open "$owd/$file" &
                unset file
            fi
        fi
    fi
done
