#!/bin/dash

file=1
while [ "$file" ]; do
    file=$(ls -a -1 --group-directories-first | /usr/bin/dmenu -b -i -p "$(basename $(pwd))")
    if [ -e "$file" ]; then
        owd=$(pwd)
        if [ -d "$file" ]; then
            cd "$file"
        else [ -f "$file" ]
            exec /usr/bin/xdg-open "$owd/$file">/dev/null 2>&1 &
            unset file
        fi
    fi
done
