#!/bin/bash
# L'option -A définit l'action action_0 dont le raccourci est défini dans
# .config/feh/keys (nécessite xclip, puisque xsel n'est pas compatible
# avec les images).

/usr/bin/feh --auto-rotate --edit --scale-down --title "%n (%wx%h, %S - zoom %z) - feh [%u/%l]" --thumb-title "%n (%wx%h, %S - zoom %z) - feh" -A 'filetype=$(file -b --mime-type %F) && xclip -selection clipboard -t $filetype -i %F' "$@"
