#!/bin/bash
. default-commands

if [ -e "${default_path}xkblayout-state" ]; then
    # Nécessite l'application xkblayout-state compilée à partir de
    # https://github.com/nonpop/xkblayout-state avec les instructions suivantes :
    # git clone https://github.com/nonpop/xkblayout-state
    # make
    keyboard_layout=$(${default_path}xkblayout-state print "%s")
    keyboard_variant=$(${default_path}xkblayout-state print "%v")
else
    # Sinon récupérer les informations à partir du fichier de configuration
    # Cf Préférences > Clavier > Éditer la configuration
    #
    # !!! Ne fonctionne que si le fichier ne contient qu'une seule disposition
    # de clavier !!!
    keyboard=$(${default_path}cat /etc/X11/xorg.conf.d/00-keyboard.conf)
    keyboard_layout=$(echo "$keyboard" | grep -ioP '^\s*Option "XkbLayout"\s*\K.*' | sed 's/\"//g')
    keyboard_variant=$(echo "$keyboard" | grep -ioP '^\s*Option "XkbVariant"\s*\K.*' | sed 's/\"//g')
fi
if [ -e "${default_path}gkbd-keyboard-display" ]; then
    if [ "$keyboard_variant" = "" ]; then
        $(urxvt -e /bin/bash -l -c "tmux new-session vim /usr/share/X11/xkb/symbols/"${keyboard_layout})
    else
        $(urxvt -e /bin/bash -l -c 'tmux new-session vim +/xkb_symbols\ \"'${keyboard_variant}'\" /usr/share/X11/xkb/symbols/'${keyboard_layout})
    fi
fi
