#!/bin/dash
# Changer la disposition du clavier.
# Permet de passer d'une disposition à l'autre parmi celles définies
# dans le fichier /etc/X11/xorg.conf.d/00-keyboard.conf
# Le raccourci clavier est défini dans .config/openbox/rc.xml

unset keyboard_layout keyboard_variant
if [ -e "/usr/bin/xkblayout-state" ]; then
    # Nécessite l'application xkblayout-state compilée à partir de
    # https://github.com/nonpop/xkblayout-state avec les instructions suivantes :
    # git clone https://github.com/nonpop/xkblayout-state
    # make
    $(/usr/bin/xkblayout-state set +1)
    keyboard_layout=$(/usr/bin/xkblayout-state print "%s")
    keyboard_variant=$(/usr/bin/xkblayout-state print "%v")
    if [ -z "$keyboard_variant" ]; then
        dunstify -r 8192 -t 2000 "Clavier : $keyboard_layout"
    else
        dunstify -r 8192 -t 2000 "Clavier : $keyboard_layout ($keyboard_variant)"
    fi
fi
