#!/bin/bash
. default-commands

# Wrapper pour contourner un bug de xautolock avec mpv :
# mpv exécute "xdg-screensaver reset" toutes les 10 secondes pour
# empêcher la mise en veille durant une vidéo (sauf en mode pause).
# xdg-screensaver exécute alors "xautolock -restart" (cf. la fonction
# xautolock_screensaver() du fichier xdg-screensaver.in à l'adresse
# https://github.com/mtorromeo/xdg-utils/blob/master/scripts/xdg-screensaver.in)
# Mais xautolock -restart est buggé et entraîne une erreur sur toute
# commande xautolock qui suivrait ("Could not locate a running xautolock")

# Options à passer en paramètres
unset mpv_options
mpv_options=" --force-window"

finish() {
    if [ ! $(${default_path}pidof -x "$0" | ${default_path}wc -w) -gt 2 ]; then 
        if [ -f "$mpv_is_xautolock" ]; then
            ${default_path}rm -f "$mpv_is_xautolock"
            ${scripts_path}suspend_script restart notification_off
        fi
    fi
}
trap finish 0 1 2 3 13 15

if [ "$(${default_path}pidof xautolock)" ]; then
    ${scripts_path}suspend_script kill notification_off
    if [ ! -f "$mpv_is_xautolock" ]; then
        ${default_path}touch "$mpv_is_xautolock"
    fi
fi

${default_path}mpv${mpv_options} --watch-later-directory=~/.local/share/mpv/watch_later --stop-screensaver=no "$@"
