#!/bin/bash

# Centralisation de variables et de fonctions pour éviter des modifications
# dans de trop nombreux fichiers en cas de changement de certains programmes
# (par ex. changement de terminal, de shell, etc.)

# Variables communes
default_path="/usr/bin/"
scripts_path="/usr/local/bin/"

# Écrire (ex. pipemenu) d'ouvrir un terminal pour éditer un fichier
function edit_file() {
    echo "${scripts_path}st -e ${scripts_path}tmux new-session ${default_path}nvim ${1}"
}

# Écrire (ex. pipemenu) d'ouvrir un terminal pour lister le contenu d'un fichier
function cat_file() {
    echo "${scripts_path}st -e ${scripts_path}tmux new-session '${default_path}cat ${1} | ${default_path}less'"
}

# Écrire d'ouvrir un terminal pour y lancer un programme
function display_file() {
    echo "${scripts_path}st -e ${scripts_path}tmux new-session '${1} | ${default_path}less'"
}

# Ouvrir un terminal pour éditer un fichier
function direct_edit_file() {
    ${scripts_path}st -e ${scripts_path}tmux new-session ${default_path}nvim "${1}"
}
