#!/bin/dash
. pipemenu-default-commands

if [ -e "${default_path}dmidecode" ]; then
    ${default_path}dmidecode --type baseboard > ${scripts_path}pipemenu-system-hardware-dmidecode-baseboard 2>&1
    ${default_path}dmidecode --type bios > ${scripts_path}pipemenu-system-hardware-dmidecode-bios 2>&1
    ${default_path}dmidecode --type memory > ${scripts_path}pipemenu-system-hardware-dmidecode-memory 2>&1
    ${default_path}dmidecode --type system > ${scripts_path}pipemenu-system-hardware-dmidecode-system 2>&1
fi
