#!/bin/bash
RESTART_ATTEMPTS=4

forcekill_conky() {
    killall -q conky
    for (( i=0; i < RESTART_ATTEMPTS; i++ )); do
        if ! pgrep -xu "$USER" "conky" &>/dev/null; then
            break
        fi
        (( i == RESTART_ATTEMPTS - 1 )) && killall -q conky
        sleep 0.5
    done
}

restart_conky(){
    if [ -e "$HOME/.config/conky/" ]; then
        unset conkyrc_list
        conkyrc_list=$(ls $HOME/.config/conky/*conkyrc* 2>/dev/null)
        if [ ! -z "$conkyrc_list" ]; then
            while IFS= read -r conkyrc_file; do
                conky -qc "$conkyrc_file"
            done <<< "$conkyrc_list"
        else
            conky -q
        fi
    else
        conky -q
    fi
}

if [[ $1 = 'stop' ]]; then
    forcekill_conky
elif [[ $1 = 'restart' ]]; then
    forcekill_conky
    if ! pgrep -xu "$USER" "conky" &>/dev/null; then
        restart_conky
    fi
fi
