#!/bin/bash
# Inspiré par le script "conkywonky"

restart_conky(){
    if [ -e "$HOME/.config/conky/" ]; then
        unset conkyrc_list
        conkyrc_list=$(ls $HOME/.config/conky/*conkyrc* 2>/dev/null)
        if [ ! -z "$conkyrc_list" ]; then
            while IFS= read -r conkyrc_file; do
                conky -qc "$conkyrc_file"
            done <<< "$conkyrc_list"
        else
            conky -q
        fi
    else
        conky -q
    fi
    exit
}

if [ "$(pidof conky)" ]; then
    killall -q conky
    sleep 1
    restart_conky
    exit
else
    restart_conky
    exit
fi
