#!/bin/bash
SCRIPTS_DIR="${HOME}/.config/mpv/scripts"
SETTINGS_DIR="${HOME}/.config/mpv/script-opts"
bold=$(tput bold)
nobold=$(tput sgr0)
yellow='\033[1;33m'
nocolor='\033[0m'

# Fonction de vérification des mises à jour
check_if_new () {
    if curl --output /dev/null --silent --head --fail "$2"; then
        if [ -f $1 ]; then
            remote_file_content=$(curl -LSs "$2")
            DIFF=$(diff <(cat "$1") <(echo "$remote_file_content"))
            if [ "$DIFF" != "" ]; then
                echo "$remote_file_content" > "$1"
                echo -e "${bold}${yellow}$1 --> mis à jour.${nocolor}${nobold}"
            else
                echo "$1 --> déjà à jour."
            fi
            unset remote_file_content DIFF
        else
            echo -e "${bold}${yellow}$1 --> le fichier n'existe pas. Il va être créé.${nocolor}${nobold}"
            curl -LSso "$1" "$2"
            echo -e "${bold}${yellow}Fichier créé.${nocolor}${nobold}"
        fi
    else
        echo -e "${bold}${yellow}$1 --> le fichier distant n'existe plus à l'adresse $2 !${nocolor}${nobold}"
    fi
}

# Mise à jour des scripts
if [ -d "${SCRIPTS_DIR}" ]; then
    echo "MISE À JOUR DES SCRIPTS :"
    # Script crop.lua pour recadrer une vidéo (uniquement à l'écran,
    # de façon temporaire)
    local_file="${SCRIPTS_DIR}/crop.lua"
    remote_file="https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/crop.lua"
    check_if_new "$local_file" "$remote_file"

    # Script encode.lua pour couper une vidéo, avec ou sans réencodage
    local_file="${SCRIPTS_DIR}/encode.lua"
    remote_file="https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/encode.lua"
    check_if_new "$local_file" "$remote_file"

    # Script Mpv-Playlistmanager
    local_file="${SCRIPTS_DIR}/playlistmanager.lua"
    remote_file="https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/master/playlistmanager.lua"
    check_if_new "$local_file" "$remote_file"
    # titleresolver.lua est une dépendance optionnelle de playlistmanager.lua
    local_file="${SCRIPTS_DIR}/titleresolver.lua"
    remote_file="https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/master/titleresolver.lua"
    check_if_new "$local_file" "$remote_file"

    # Script cycle-commands pour permettre de définir des raccourcis
    # avec plusieurs commandes même quand certaines sont identiques,
    # par exemple pour changer le style des sous-titres
    local_file="${SCRIPTS_DIR}/cycle-commands.lua"
    remote_file="https://raw.githubusercontent.com/CogentRedTester/mpv-scripts/master/cycle-commands.lua"
    check_if_new "$local_file" "$remote_file"

    # Script cycle-video_rotate pour des rotations cohérentes
    local_file="${SCRIPTS_DIR}/cycle-video-rotate.lua"
    remote_file="https://raw.githubusercontent.com/VideoPlayerCode/mpv-tools/master/scripts/cycle-video-rotate.lua"
    check_if_new "$local_file" "$remote_file"
else
    echo "Erreur : le dossier ${SCRIPTS_DIR} n'existe pas."
fi

echo

# Mise à jour des fichiers de configuration par défaut
if [[ -d "${SETTINGS_DIR}" ]]; then
    echo "MISE À JOUR DES FICHIERS DE CONFIGURATION :"
    local_file="${SETTINGS_DIR}/default_reenc.conf"
    remote_file="https://raw.githubusercontent.com/occivink/mpv-scripts/master/script-opts/encode_webm.conf"
    check_if_new "$local_file" "$remote_file"

    local_file="${SETTINGS_DIR}/default_slice.conf"
    remote_file="https://raw.githubusercontent.com/occivink/mpv-scripts/master/script-opts/encode_slice.conf"
    check_if_new "$local_file" "$remote_file"

    local_file="${SETTINGS_DIR}/default_crop.conf"
    remote_file="https://raw.githubusercontent.com/occivink/mpv-scripts/master/script-opts/crop.conf"
    check_if_new "$local_file" "$remote_file"

    local_file="${SETTINGS_DIR}/default_playlistmanager.conf"
    remote_file="https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/master/playlistmanager.conf"
    check_if_new "$local_file" "$remote_file"
else
    echo "Erreur : le dossier ${SETTINGS_DIR} n'existe pas."
fi
