#!/bin/dash

# xdesktop : https://github.com/onodera-punpun/xdesktop
# xtitle : https://github.com/baskerville/xtitle (modifié avant compilation ! dans xtitle.c :
# ligne 263 (dernière ligne de la fonction "bool title_changed") : remplacer "return false;" par "return true;"
# xwinfo : https://github.com/baskerville/xwinfo
xtitle -s | while read xtitle; do
    desktop_active=$(xdesktop)
    desktop_active=$(($desktop_active-1))
    windows=$(wmctrl -lp | grep "  $desktop_active ")
    window_str=''
    if [ ! -z "$windows" ]; then
        window_active_id=$(wmctrl -lp | grep $(xprop -root | grep _NET_ACTIVE_WINDOW | grep "id #" | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/') | awk '{print $1}')
        echo "$windows" | ( while IFS= read -r window; do
        window_id=$(echo $window | awk -F ' ' '{print $1}')
        window_name=$(xwinfo -c $window_id)
        if [ "$window_name" != "N/A" ]; then
            if [ "$window_name" = "st-256color" ]; then
                window_name="st"
            fi
            if [ "$window_id" = "$window_active_id" ]; then
                window_name="%{A:xdotool windowminimize $window_id &:} %{T2}$window_name%{T-} %{A}"
            else
                window_name="%{A:xdotool windowactivate $window_id &:} $window_name %{A}"
            fi
            if [ ! -z "$window_str" ]; then
                separator="  |  "
            else
                separator=''
            fi
            window_str="${window_str}${separator}${window_name}"
        fi
        done
        echo "$window_str" )
    else
        echo " "
    fi
done
