#!/bin/bash
. default-commands
. pipemenu-system-functions

echo "<openbox_pipe_menu>"

unset is_board
if [ -e "${scripts_path}pipemenu-system-hardware-dmidecode-baseboard" ]; then
    IFS=$' '
    board=$(cat ${scripts_path}pipemenu-system-hardware-dmidecode-baseboard)
    unset board_name
    board_name=$(echo "$board" | grep -ioP '^\s*Product Name:\K.*')
    if [ ! -z "$board_name" ]; then
        is_board=1
        board_name=$(sanityse_output "$board_name")
        echo "<item label=\"Modèle : $board_name\" />"
    fi
    unset board_vendor
    board_vendor=$(echo "$board" | grep -ioP '^\s*Manufacturer:\K.*')
    if [ ! -z "$board_vendor" ]; then
        is_board=1
        board_vendor=$(sanityse_output_with_quotes "$board_vendor")
        echo "<item label=\"Fabricant : $board_vendor\" />"
    fi
    unset board_version
    board_version=$(echo "$board" | grep -ioP '^\s*Version:\K.*')
    if [ ! -z "$board_version" ]; then
        is_board=1
        board_version=$(sanityse_output "$board_version")
        echo "<item label=\"Version : $board_version\" />"
    fi
    unset board_serial_number
    board_serial_number=$(echo "$board" | grep -ioP '^\s*Serial Number:\K.*')
    if [ ! -z "$board_serial_number" ]; then
        is_board=1
        board_serial_number=$(sanityse_output "$board_serial_number")
        echo "<item label=\"N° de série : $board_serial_number\" />"
    fi
    unset IFS
    if [ ! -z "$is_board" ]; then
        echo "<separator />"
        echo "<item label=\"Afficher plus d'informations (dmidecode)\"><action name=\"Execute\"><command>$(cat_file "${scripts_path}pipemenu-system-hardware-dmidecode-baseboard")</command></action></item>"
    fi
fi

if [ -z "$is_board" ]; then
    if [ -e "/sys/devices/virtual/dmi/id/board_name" ]; then
        unset board_name
        board_name=$(cat /sys/devices/virtual/dmi/id/board_name)
        if [ ! -z "$board_name" ]; then
            is_board=1
            board_name=$(sanityse_output "$board_name")
            echo "<item label=\"Modèle : $board_name\" />"
        fi
    fi
    if [ -e "/sys/devices/virtual/dmi/id/board_vendor" ]; then
        unset board_vendor
        board_vendor=$(cat /sys/devices/virtual/dmi/id/board_vendor)
        if [ ! -z "$board_vendor" ]; then
            is_board=1
            board_vendor=$(sanityse_output_with_quotes "$board_vendor")
            echo "<item label=\"Fabricant : $board_vendor\" />"
        fi
    fi
fi

if [ -z "$is_board" ]; then
    echo "<item label=\"Carte mère non reconnue.\" />"
fi

echo "</openbox_pipe_menu>"
exit 0
